### ISSUE TITLE
 (ToDo + WIP) MFEM 4.5.2+ Python 3.11 

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/PyMFEM#166]
[Placeholder. Goals after PyMFEM 4.5.2 (https://github.com/mfem/PyMFEM/releases/tag/v4.5.2)
- [ ] Include test with Python3.11
- [x] numba 0.57
- [x] fix examples for numpy 1.24 https://github.com/mfem/PyMFEM/pull/176
- [ ] PETSc  https://github.com/mfem/PyMFEM/pull/162
- [ ] Include GSlib as a binary release
- [x] https://github.com/mfem/PyMFEM/pull/175
