### ISSUE TITLE
ToDo  for PyMFEM 4.4

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/PyMFEM#98]
ToDo list
- [x] DenseTensor Constructor from numpy array (4.3.0.1)
- [ ] hypre mixedint support?
- [x] ex25, ex25p, ex30, ex30p
- [ ]  ex31, ex31p, ex32p
- [ ] HYPRE_USE_CUDA
- [x] gslib
- [x] distant_solver
- [x] migrate test in cuda 11.5
- [x] symmat.hpp
- [x] redo Array <T> constructor to support MemoryType

After 4.4 
- [ ] Strumpack
- [ ] Binary release for Mac
- [ ] libCeed Algebraic Solver

**Comment by sshiraiwa** [comment]
Closing this
